"""create events table

Revision ID: adf4b17bb088
Revises: 
Create Date: 2026-06-03 22:16:57.374782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf4b17bb088'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_approved', sa.Boolean(), nullable=False),
    sa.Column('risk_reason', sa.String(), nullable=True),
    sa.Column('order_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('asset', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.CheckConstraint("event_type IN ('ORDER_SUBMITTED', 'ORDER_CANCELLED', 'ORDER_FILLED', 'RISK_CHECK_REQUESTED')", name='ck_events_event_type_valid'),
    sa.CheckConstraint("side IN ('BUY', 'SELL')", name='ck_events_side_valid'),
    sa.CheckConstraint("status IN ('accepted', 'rejected')", name='ck_events_status_valid'),
    sa.CheckConstraint('char_length(asset) BETWEEN 1 AND 30', name='ck_events_asset_length_valid'),
    sa.CheckConstraint('order_value > 0', name='ck_events_order_value_positive'),
    sa.CheckConstraint('price > 0', name='ck_events_price_positive'),
    sa.CheckConstraint('quantity > 0', name='ck_events_quantity_positive'),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
