"""Fix tenants table

Revision ID: af92313a2cbe
Revises: ab05c81b195c
Create Date: 2026-07-07 20:25:50.244350

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "af92313a2cbe"
down_revision: Union[str, Sequence[str], None] = "ab05c81b195c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
