"""Update name in api_keys table

Revision ID: c11b2a2a597c
Revises: af92313a2cbe
Create Date: 2026-07-07 20:34:36.383867

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c11b2a2a597c"
down_revision: Union[str, Sequence[str], None] = "af92313a2cbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_keys", sa.Column("api_key_name", sa.String(length=100), nullable=False)
    )
    op.drop_column("api_keys", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_keys",
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.drop_column("api_keys", "api_key_name")
    # ### end Alembic commands ###
