"""create tenants table

Revision ID: df86402e5db2
Revises: adf4b17bb088
Create Date: 2026-06-06 17:25:28.530722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df86402e5db2'
down_revision: Union[str, Sequence[str], None] = 'adf4b17bb088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('char_length(tenant_name) BETWEEN 1 AND 100', name='ck_tenants_tenant_name_length_valid'),
    sa.PrimaryKeyConstraint('tenant_id'),
    sa.UniqueConstraint('tenant_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenants')
    # ### end Alembic commands ###
